### ISSUE TITLE
Investigate MSAN on eccvm_recursion_tests 

### ISSUE THREAD

**Issue by maramihali** [AztecProtocol/barretenberg#1077]

**Comment by codygunton** [comment]
@maramihali was there a particular error that caused you to make this issue? I can't find a reference to this issue in the code.

**Comment by maramihali** [comment]
Reproducer, to run bb with MSAN we have a dedicated instance:
`./scripts/docker_interactive.sh msan.ubuntu` from `cpp`
Then `cmake --preset msan` and `cmake --build . --parallel --target stdlib_eccvm_verifier_tests`. 

You might get a weird error at linking time but everything has been built already and you should be able to run tests:
```
cmake --build . --parallel --target stdlib_eccvm_verifier_tests
[2/168] Performing download step (git clone) for 'msgpack-c'
Cloning into 'msgpack-c'...
HEAD is now at 492d78fc Update cpp11_zone.hpp
[168/168] Linking CXX executable bin/stdlib_eccvm_verifier_tests
FAILED: bin/stdlib_eccvm_verifier_tests src/barretenberg/stdlib/eccvm_verifier/stdlib_eccvm_verifier_tests[1]_tests.cmake /usr/src/barretenberg/cpp/build-msan/src/barretenberg/stdlib/eccvm_verifier/stdlib_eccvm_verifier_tests[1]_tests.cmake 
: && /usr/bin/clang++-16 -std=c++20 -fsanitize=memory -fsanitize-memory-track-origins -nostdinc++ -I/opt/include -I/opt/include/c++/v1 -g -fsanitize=memory -fsanitize-memory-track-origins -stdlib=libc++ -L/opt/lib -lc++abi -Wl,-rpath,/opt/lib    -pthread src/barretenberg/stdlib/eccvm_verifier/CMakeFiles/stdlib_eccvm_verifier_test_objects.dir/ecc_relation_consistency.test.cpp.o src/barretenberg/stdlib/eccvm_verifier/CMakeFiles/stdlib_eccvm_verifier_test_objects.dir/eccvm_recursive_verifier.test.cpp.o src/barretenberg/stdlib/eccvm_verifier/CMakeFiles/stdlib_eccvm_verifier_test_objects.dir/verifier_commitment_key.test.cpp.o -o bin/stdlib_eccvm_verifier_tests  lib/libstdlib_eccvm_verifier.a  lib/libeccvm.a  lib/libstdlib_transcript.a  lib/libgtest.a  lib/libgtest_main.a  lib/libgmock_main.a  lib/libstdlib_poseidon2.a  lib/libstdlib_primitives.a  lib/libcircuit_checker.a  lib/libsumcheck.a  lib/libstdlib_circuit_builders.a  lib/libtrace_to_polynomials.a  lib/libplonk_honk_shared.a  lib/libultra_honk.a  lib/libsumcheck.a  lib/libstdlib_circuit_builders.a  lib/libtrace_to_polynomials.a  lib/libplonk_honk_shared.a  lib/libultra_honk.a  lib/libtranscript.a  lib/librelations.a  lib/libcrypto_pedersen_hash.a  lib/libcrypto_pedersen_commitment.a  lib/libsrs.a  lib/libpolynomials.a  lib/libcrypto_poseidon2.a  lib/libecc.a  lib/libnumeric.a  lib/libcommon.a  lib/libenv.a  lib/libcrypto_sha256.a  lib/libcrypto_keccak.a  lib/libgmock.a  lib/libgtest.a && cd /usr/src/barretenberg/cpp/build-msan/src/barretenberg/stdlib/eccvm_verifier && /usr/bin/cmake -D TEST_TARGET=stdlib_eccvm_verifier_tests -D TEST_EXECUTABLE=/usr/src/barretenberg/cpp/build-msan/bin/stdlib_eccvm_verifier_tests -D TEST_EXECUTOR= -D TEST_WORKING_DIR=/usr/src/barretenberg/cpp/build-msan -D TEST_EXTRA_ARGS= -D TEST_PROPERTIES= -D TEST_PREFIX= -D TEST_SUFFIX= -D "TEST_FILTER=-*_SKIP_CI*" -D NO_PRETTY_TYPES=FALSE -D NO_PRETTY_VALUES=FALSE -D TEST_LIST=stdlib_eccvm_verifier_tests_TESTS -D CTEST_FILE=/usr/src/barretenberg/cpp/build-msan/src/barretenberg/stdlib/eccvm_verifier/stdlib_eccvm_verifier_tests[1]_tests.cmake -D TEST_DISCOVERY_TIMEOUT=5 -D TEST_XML_OUTPUT_DIR= -P /usr/share/cmake-3.25/Modules/GoogleTestAddTests.cmake
clang: warning: argument unused during compilation: '-nostdinc++' [-Wunused-command-line-argument]
FATAL: Code 0x62ec67b86b80 is out of application range. Non-PIE build?
FATAL: MemorySanitizer can not mmap the shadow memory.
FATAL: Make sure to compile with -fPIE and to link with -pie.
FATAL: Disabling ASLR is known to cause this error.
FATAL: If running under GDB, try 'set disable-randomization off'.
==1353==Process memory map follows:
        0x62ec67b1c000-0x62ec67b5a000   /usr/src/barretenberg/cpp/build-msan/bin/stdlib_eccvm_verifier_tests
        0x62ec67b5a000-0x62ec79443000   /usr/src/barretenberg/cpp/build-msan/bin/stdlib_eccvm_verifier_tests
        0x62ec79443000-0x62ec7b0e8000   /usr/src/barretenberg/cpp/build-msan/bin/stdlib_eccvm_verifier_tests
        0x62ec7b0e8000-0x62ec7b0f2000   /usr/src/barretenberg/cpp/build-msan/bin/stdlib_eccvm_verifier_tests
        0x62ec7b0f2000-0x62ec7b0f6000   /usr/src/barretenberg/cpp/build-msan/bin/stdlib_eccvm_verifier_tests
        0x62ec7b0f6000-0x62ec7d124000
        0x73e8c9a00000-0x73e8c9b00000
        0x73e8c9c00000-0x73e8c9d00000
        0x73e8c9e00000-0x73e8c9f00000
        0x73e8ca000000-0x73e8ca100000
        0x73e8ca200000-0x73e8ca300000
        0x73e8ca400000-0x73e8ca78e000
        0x73e8ca961000-0x73e8caa71000
        0x73e8caa71000-0x73e8caa73000   /usr/lib/x86_64-linux-gnu/libatomic.so.1.2.0
        0x73e8caa73000-0x73e8caa76000   /usr/lib/x86_64-linux-gnu/libatomic.so.1.2.0
        0x73e8caa76000-0x73e8caa78000   /usr/lib/x86_64-linux-gnu/libatomic.so.1.2.0
        0x73e8caa78000-0x73e8caa79000   /usr/lib/x86_64-linux-gnu/libatomic.so.1.2.0
        0x73e8caa79000-0x73e8caa7a000   /usr/lib/x86_64-linux-gnu/libatomic.so.1.2.0
        0x73e8caa7a000-0x73e8caa7b000
        0x73e8caa7b000-0x73e8caa9d000   /usr/lib/x86_64-linux-gnu/libc.so.6
        0x73e8caa9d000-0x73e8cac15000   /usr/lib/x86_64-linux-gnu/libc.so.6
        0x73e8cac15000-0x73e8cac6d000   /usr/lib/x86_64-linux-gnu/libc.so.6
        0x73e8cac6d000-0x73e8cac71000   /usr/lib/x86_64-linux-gnu/libc.so.6
        0x73e8cac71000-0x73e8cac73000   /usr/lib/x86_64-linux-gnu/libc.so.6
        0x73e8cac73000-0x73e8cac82000
        0x73e8cac82000-0x73e8cac85000   /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
        0x73e8cac85000-0x73e8caca0000   /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
        0x73e8caca0000-0x73e8caca4000   /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
        0x73e8caca4000-0x73e8caca5000   /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
        0x73e8caca5000-0x73e8caca6000   /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
        0x73e8caca6000-0x73e8caca9000   /usr/lib/x86_64-linux-gnu/libresolv.so.2
        0x73e8caca9000-0x73e8cacb2000   /usr/lib/x86_64-linux-gnu/libresolv.so.2
        0x73e8cacb2000-0x73e8cacb5000   /usr/lib/x86_64-linux-gnu/libresolv.so.2
        0x73e8cacb5000-0x73e8cacb6000   /usr/lib/x86_64-linux-gnu/libresolv.so.2
        0x73e8cacb6000-0x73e8cacb7000   /usr/lib/x86_64-linux-gnu/libresolv.so.2
        0x73e8cacb7000-0x73e8cacb9000
        0x73e8cacb9000-0x73e8cacc7000   /usr/lib/x86_64-linux-gnu/libm.so.6
        0x73e8cacc7000-0x73e8cad45000   /usr/lib/x86_64-linux-gnu/libm.so.6
        0x73e8cad45000-0x73e8cada0000   /usr/lib/x86_64-linux-gnu/libm.so.6
        0x73e8cada0000-0x73e8cada1000   /usr/lib/x86_64-linux-gnu/libm.so.6
        0x73e8cada1000-0x73e8cada2000   /usr/lib/x86_64-linux-gnu/libm.so.6
        0x73e8cada2000-0x73e8cada9000
        0x73e8cada9000-0x73e8cade7000   /opt/lib/libc++.so.1.0
        0x73e8cade7000-0x73e8cb440000   /opt/lib/libc++.so.1.0
        0x73e8cb440000-0x73e8cb4d2000   /opt/lib/libc++.so.1.0
        0x73e8cb4d2000-0x73e8cb4d8000   /opt/lib/libc++.so.1.0
        0x73e8cb4d8000-0x73e8cb4da000   /opt/lib/libc++.so.1.0
        0x73e8cb4da000-0x73e8cb4f7000
        0x73e8cb4f7000-0x73e8cb507000   /opt/lib/libc++abi.so.1.0
        0x73e8cb507000-0x73e8cb6a3000   /opt/lib/libc++abi.so.1.0
        0x73e8cb6a3000-0x73e8cb6c8000   /opt/lib/libc++abi.so.1.0
        0x73e8cb6c8000-0x73e8cb6cc000   /opt/lib/libc++abi.so.1.0
        0x73e8cb6cc000-0x73e8cb6cd000   /opt/lib/libc++abi.so.1.0
        0x73e8cb6cd000-0x73e8cb6d4000
        0x73e8cb6d4000-0x73e8cb6d5000   /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
        0x73e8cb6d5000-0x73e8cb6fd000   /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
        0x73e8cb6fd000-0x73e8cb707000   /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
        0x73e8cb707000-0x73e8cb709000   /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
        0x73e8cb709000-0x73e8cb70b000   /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
        0x7ffcaf4a0000-0x7ffcaf4c1000   [stack]
        0x7ffcaf5c7000-0x7ffcaf5cb000   [vvar]
        0x7ffcaf5cb000-0x7ffcaf5cd000   [vdso]
        0xffffffffff600000-0xffffffffff601000   [vsyscall]
==1353==End of process memory map.
CMake Error at /usr/share/cmake-3.25/Modules/GoogleTestAddTests.cmake:112 (message):
  Error running test executable.

    Path: '/usr/src/barretenberg/cpp/build-msan/bin/stdlib_eccvm_verifier_tests'
    Result: 1
    Output:
      

Call Stack (most recent call first):
  /usr/share/cmake-3.25/Modules/GoogleTestAddTests.cmake:225 (gtest_discover_tests_impl)


ninja: build stopped: subcommand failed.
```
Runing MSAN we get the following output and we need to validate whether it is an actual problem or a false positive
```

Running main() from /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest_main.cc
[==========] Running 5 tests from 4 test suites.
[----------] Global test environment set-up.
[----------] 1 test from EccRelationsConsistency
[ RUN      ] EccRelationsConsistency.RecursiveToNativeConsistency
[       OK ] EccRelationsConsistency.RecursiveToNativeConsistency (4873 ms)
[----------] 1 test from EccRelationsConsistency (4873 ms total)

[----------] 2 tests from ECCVMRecursiveTests/0, where TypeParam = bb::ECCVMRecursiveFlavor_<bb::UltraCircuitBuilder_<bb::UltraExecutionTraceBlocks>>
[ RUN      ] ECCVMRecursiveTests/0.SingleRecursiveVerification
ECCVM Recursive Verifier
Recursive Verifier: num gates = 338385
Finalized circuit size: 338553
Log dyadic circuit size: 19
==1563==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x5b7e1bd6950b in unsigned int bb::scalar_multiplication::construct_addition_chains<bb::curve::BN254>(bb::scalar_multiplication::affine_product_runtime_state<bb::curve::BN254>&, bool) /usr/src/barretenberg/cpp/src/barretenberg/ecc/scalar_multiplication/scalar_multiplication.cpp:649:21
    #1 0x5b7e1beda28c in bb::curve::BN254::AffineElement* bb::scalar_multiplication::reduce_buckets<bb::curve::BN254>(bb::scalar_multiplication::affine_product_runtime_state<bb::curve::BN254>&, bool, bool) /usr/src/barretenberg/cpp/src/barretenberg/ecc/scalar_multiplication/scalar_multiplication.cpp:514:36
    #2 0x5b7e1c0aaea8 in bb::curve::BN254::Element bb::scalar_multiplication::evaluate_pippenger_rounds<bb::curve::BN254>(bb::scalar_multiplication::pippenger_runtime_state<bb::curve::BN254>&, std::__1::span<bb::curve::BN254::AffineElement const, 18446744073709551615ul>, unsigned long, bool)::'lambda'(unsigned long)::operator()(unsigned long) const /usr/src/barretenberg/cpp/src/barretenberg/ecc/scalar_multiplication/scalar_multiplication.cpp:828:49
    #3 0x5b7e1c0a879c in decltype(std::declval<bb::curve::BN254>()(std::declval<unsigned long>())) std::__1::__invoke[abi:v160006]<bb::curve::BN254::Element bb::scalar_multiplication::evaluate_pippenger_rounds<bb::curve::BN254>(bb::scalar_multiplication::pippenger_runtime_state<bb::curve::BN254>&, std::__1::span<bb::curve::BN254::AffineElement const, 18446744073709551615ul>, unsigned long, bool)::'lambda'(unsigned long)&, unsigned long>(bb::curve::BN254&&, unsigned long&&) /opt/include/c++/v1/__functional/invoke.h:394:23
    #4 0x5b7e1c0a8522 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<bb::curve::BN254::Element bb::scalar_multiplication::evaluate_pippenger_rounds<bb::curve::BN254>(bb::scalar_multiplication::pippenger_runtime_state<bb::curve::BN254>&, std::__1::span<bb::curve::BN254::AffineElement const, 18446744073709551615ul>, unsigned long, bool)::'lambda'(unsigned long)&, unsigned long>(bb::curve::BN254::Element bb::scalar_multiplication::evaluate_pippenger_rounds<bb::curve::BN254>(bb::scalar_multiplication::pippenger_runtime_state<bb::curve::BN254>&, std::__1::span<bb::curve::BN254::AffineElement const, 18446744073709551615ul>, unsigned long, bool)::'lambda'(unsigned long)&, unsigned long&&) /opt/include/c++/v1/__functional/invoke.h:487:9
    #5 0x5b7e1c0a83af in std::__1::__function::__alloc_func<bb::curve::BN254::Element bb::scalar_multiplication::evaluate_pippenger_rounds<bb::curve::BN254>(bb::scalar_multiplication::pippenger_runtime_state<bb::curve::BN254>&, std::__1::span<bb::curve::BN254::AffineElement const, 18446744073709551615ul>, unsigned long, bool)::'lambda'(unsigned long), std::__1::allocator<bb::curve::BN254::Element bb::scalar_multiplication::evaluate_pippenger_rounds<bb::curve::BN254>(bb::scalar_multiplication::pippenger_runtime_state<bb::curve::BN254>&, std::__1::span<bb::curve::BN254::AffineElement const, 18446744073709551615ul>, unsigned long, bool)::'lambda'(unsigned long)>, void (unsigned long)>::operator()[abi:v160006](unsigned long&&) /opt/include/c++/v1/__functional/function.h:185:16
    #6 0x5b7e1c0a1a4e in std::__1::__function::__func<bb::curve::BN254::Element bb::scalar_multiplication::evaluate_pippenger_rounds<bb::curve::BN254>(bb::scalar_multiplication::pippenger_runtime_state<bb::curve::BN254>&, std::__1::span<bb::curve::BN254::AffineElement const, 18446744073709551615ul>, unsigned long, bool)::'lambda'(unsigned long), std::__1::allocator<bb::curve::BN254::Element bb::scalar_multiplication::evaluate_pippenger_rounds<bb::curve::BN254>(bb::scalar_multiplication::pippenger_runtime_state<bb::curve::BN254>&, std::__1::span<bb::curve::BN254::AffineElement const, 18446744073709551615ul>, unsigned long, bool)::'lambda'(unsigned long)>, void (unsigned long)>::operator()(unsigned long&&) /opt/include/c++/v1/__functional/function.h:356:12
    #7 0x5b7e1c17435e in std::__1::__function::__value_func<void (unsigned long)>::operator()[abi:v160006](unsigned long&&) const /opt/include/c++/v1/__functional/function.h:510:16
    #8 0x5b7e1c17404f in std::__1::function<void (unsigned long)>::operator()(unsigned long) const /opt/include/c++/v1/__functional/function.h:1156:12
    #9 0x5b7e1c165046 in (anonymous namespace)::ThreadPool::do_iterations() /usr/src/barretenberg/cpp/src/barretenberg/common/parallel_for_mutex_pool.cpp:70:13
    #10 0x5b7e1c15fb48 in (anonymous namespace)::ThreadPool::worker_loop(unsigned long) /usr/src/barretenberg/cpp/src/barretenberg/common/parallel_for_mutex_pool.cpp:114:9
    #11 0x5b7e1c163865 in decltype(*std::declval<(anonymous namespace)::ThreadPool*>().*std::declval<void ((anonymous namespace)::ThreadPool::*)(unsigned long)>()(std::declval<unsigned long>())) std::__1::__invoke[abi:v160006]<void ((anonymous namespace)::ThreadPool::*)(unsigned long), (anonymous namespace)::ThreadPool*, unsigned long, void>(void ((anonymous namespace)::ThreadPool::*&&)(unsigned long), (anonymous namespace)::ThreadPool*&&, unsigned long&&) /opt/include/c++/v1/__functional/invoke.h:359:23
    #12 0x5b7e1c16345f in void std::__1::__thread_execute[abi:v160006]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ((anonymous namespace)::ThreadPool::*)(unsigned long), (anonymous namespace)::ThreadPool*, unsigned long, 2ul, 3ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ((anonymous namespace)::ThreadPool::*)(unsigned long), (anonymous namespace)::ThreadPool*, unsigned long>&, std::__1::__tuple_indices<2ul, 3ul>) /opt/include/c++/v1/thread:282:5
    #13 0x5b7e1c161ee7 in void* std::__1::__thread_proxy[abi:v160006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ((anonymous namespace)::ThreadPool::*)(unsigned long), (anonymous namespace)::ThreadPool*, unsigned long>>(void*) /opt/include/c++/v1/thread:293:5
    #14 0x7cc44ffd06b9  (/lib/x86_64-linux-gnu/libc.so.6+0x8f6b9) (BuildId: d320ce4e63925d698610ed423fc4b1f0e8ed51f1)
    #15 0x7cc45005f043 in clone (/lib/x86_64-linux-gnu/libc.so.6+0x11e043) (BuildId: d320ce4e63925d698610ed423fc4b1f0e8ed51f1)

  Uninitialized value was created by a heap allocation
    #0 0x5b7e0a8ece8e in aligned_alloc (/usr/src/barretenberg/cpp/build-msan/bin/stdlib_eccvm_verifier_tests+0x6fe8e) (BuildId: 90a5454d11b5a2faf6eb28a1d99e02b42346e129)
    #1 0x5b7e1a91cfde in protected_aligned_alloc(unsigned long, unsigned long) /usr/src/barretenberg/cpp/src/barretenberg/common/mem.hpp:70:9
    #2 0x5b7e1c106d6b in (anonymous namespace)::SlabAllocator::get(unsigned long) /usr/src/barretenberg/cpp/src/barretenberg/common/slab_allocator.cpp:182:18
    #3 0x5b7e1c10593f in bb::get_mem_slab(unsigned long) /usr/src/barretenberg/cpp/src/barretenberg/common/slab_allocator.cpp:217:22
    #4 0x5b7e1bd1cc4a in bb::scalar_multiplication::pippenger_runtime_state<bb::curve::BN254>::pippenger_runtime_state(unsigned long) /usr/src/barretenberg/cpp/src/barretenberg/ecc/scalar_multiplication/runtime_states.cpp:27:11
    #5 0x5b7e0b1926f9 in bb::CommitmentKey<bb::curve::BN254>::CommitmentKey(unsigned long) /usr/src/barretenberg/cpp/src/barretenberg/commitment_schemes/commitment_key.hpp:69:11
    #6 0x5b7e0b1924d4 in bb::CommitmentKey<bb::curve::BN254>* std::__1::construct_at[abi:v160006]<bb::CommitmentKey<bb::curve::BN254>, unsigned long&, bb::CommitmentKey<bb::curve::BN254>*>(bb::CommitmentKey<bb::curve::BN254>*, unsigned long&) /opt/include/c++/v1/__memory/construct_at.h:38:48
    #7 0x5b7e0b191882 in void std::__1::allocator_traits<std::__1::allocator<bb::CommitmentKey<bb::curve::BN254>>>::construct[abi:v160006]<bb::CommitmentKey<bb::curve::BN254>, unsigned long&, void, void>(std::__1::allocator<bb::CommitmentKey<bb::curve::BN254>>&, bb::CommitmentKey<bb::curve::BN254>*, unsigned long&) /opt/include/c++/v1/__memory/allocator_traits.h:304:9
    #8 0x5b7e0b190381 in std::__1::__shared_ptr_emplace<bb::CommitmentKey<bb::curve::BN254>, std::__1::allocator<bb::CommitmentKey<bb::curve::BN254>>>::__shared_ptr_emplace[abi:v160006]<unsigned long&>(std::__1::allocator<bb::CommitmentKey<bb::curve::BN254>>, unsigned long&) /opt/include/c++/v1/__memory/shared_ptr.h:284:13
    #9 0x5b7e0b18f99a in std::__1::shared_ptr<bb::CommitmentKey<bb::curve::BN254>> std::__1::allocate_shared[abi:v160006]<bb::CommitmentKey<bb::curve::BN254>, std::__1::allocator<bb::CommitmentKey<bb::curve::BN254>>, unsigned long&, void>(std::__1::allocator<bb::CommitmentKey<bb::curve::BN254>> const&, unsigned long&) /opt/include/c++/v1/__memory/shared_ptr.h:995:55
    #10 0x5b7e0b186516 in std::__1::shared_ptr<bb::CommitmentKey<bb::curve::BN254>> std::__1::make_shared[abi:v160006]<bb::CommitmentKey<bb::curve::BN254>, unsigned long&, void>(unsigned long&) /opt/include/c++/v1/__memory/shared_ptr.h:1004:12
    #11 0x5b7e136bf317 in bb::DeciderProver_<bb::UltraFlavor>::execute_pcs_rounds() /usr/src/barretenberg/cpp/src/barretenberg/ultra_honk/decider_prover.cpp:63:20
    #12 0x5b7e136c69fd in bb::DeciderProver_<bb::UltraFlavor>::construct_proof() /usr/src/barretenberg/cpp/src/barretenberg/ultra_honk/decider_prover.cpp:105:5
    #13 0x5b7e1344d3e6 in bb::UltraProver_<bb::UltraFlavor>::construct_proof() /usr/src/barretenberg/cpp/src/barretenberg/ultra_honk/ultra_prover.cpp:67:20
    #14 0x5b7e0ab64f19 in bb::ECCVMRecursiveTests<bb::ECCVMRecursiveFlavor_<bb::UltraCircuitBuilder_<bb::UltraExecutionTraceBlocks>>>::test_recursive_verification() (/usr/src/barretenberg/cpp/build-msan/bin/stdlib_eccvm_verifier_tests+0x2e7f19) (BuildId: 90a5454d11b5a2faf6eb28a1d99e02b42346e129)
    #15 0x5b7e0ab6145c in bb::ECCVMRecursiveTests_SingleRecursiveVerification_Test<bb::ECCVMRecursiveFlavor_<bb::UltraCircuitBuilder_<bb::UltraExecutionTraceBlocks>>>::TestBody() (/usr/src/barretenberg/cpp/build-msan/bin/stdlib_eccvm_verifier_tests+0x2e445c) (BuildId: 90a5454d11b5a2faf6eb28a1d99e02b42346e129)
    #16 0x5b7e0e113e74 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2621:10
    #17 0x5b7e0df75101 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2657:14
    #18 0x5b7e0dedda48 in testing::Test::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2696:5
    #19 0x5b7e0dee10bb in testing::TestInfo::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2845:11

SUMMARY: MemorySanitizer: use-of-uninitialized-value /usr/src/barretenberg/cpp/src/barretenberg/ecc/scalar_multiplication/scalar_multiplication.cpp:649:21 in unsigned int bb::scalar_multiplication::construct_addition_chains<bb::curve::BN254>(bb::scalar_multiplication::affine_product_runtime_state<bb::curve::BN254>&, bool)
Exiting
```

It will point to some prefetches that can be removed for debugging (also Adam was pointing out it's bad that we don't bound-check before prefetching). I didn't have time to look more into this but  I hope this is a good starting point.

**Comment by iakovenkos** [comment]
The code msan complained about got refactored as a part of https://github.com/AztecProtocol/aztec-packages/pull/14907, so now we're checking the bounds while prefetching
