### ISSUE TITLE
MSAN: ECCVM

### ISSUE THREAD

**Issue by ludamad** [AztecProtocol/barretenberg#860]
```
[----------] 2 tests from ECCVMComposerTests/0, where TypeParam = bb::ECCVMFlavor
[ RUN      ] ECCVMComposerTests/0.BaseCase
==1836==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55778e500b1a in bb::field<bb::Bn254FqParams>::montgomery_mul(bb::field<bb::Bn254FqParams> const&) const /usr/src/barretenberg/cpp/src/barretenberg/ecc/curves/bn254/../../fields/./field_impl_generic.hpp:467:12
    #1 0x55778e500b1a in bb::field<bb::Bn254FqParams>::operator*(bb::field<bb::Bn254FqParams> const&) const /usr/src/barretenberg/cpp/src/barretenberg/ecc/curves/bn254/../../fields/./field_impl.hpp:33:16
    #2 0x55778e500b1a in bb::ECCVMProver_<bb::ECCVMFlavor>::execute_transcript_consistency_univariate_opening_round() /usr/src/barretenberg/cpp/src/barretenberg/eccvm/eccvm_prover.cpp:265:36
    #3 0x55778e515f0d in bb::ECCVMProver_<bb::ECCVMFlavor>::construct_proof() /usr/src/barretenberg/cpp/src/barretenberg/eccvm/eccvm_prover.cpp:305:5
    #4 0x55778db7fb8d in ECCVMComposerTests_BaseCase_Test<bb::ECCVMFlavor>::TestBody() /usr/src/barretenberg/cpp/src/barretenberg/eccvm/eccvm_composer.test.cpp:80:25
    #5 0x55779031a794 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2621:10
    #6 0x5577901770e1 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2657:14
    #7 0x5577900df6a8 in testing::Test::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2696:5
    #8 0x5577900e2d1b in testing::TestInfo::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2845:11
    #9 0x5577900e5c7b in testing::TestSuite::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:3004:30
    #10 0x557790125f26 in testing::internal::UnitTestImpl::RunAllTests() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:5890:44
    #11 0x55779031ded4 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2621:10
    #12 0x557790186f6d in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2657:14
    #13 0x557790123c5f in testing::UnitTest::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:5455:10
    #14 0x557790325b60 in RUN_ALL_TESTS() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/include/gtest/gtest.h:2314:73
    #15 0x557790325b49 in main /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest_main.cc:63:10
    #16 0x7ffb6d04ea8f  (/lib/x86_64-linux-gnu/libc.so.6+0x23a8f) (BuildId: d320ce4e63925d698610ed423fc4b1f0e8ed51f1)
    #17 0x7ffb6d04eb48 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x23b48) (BuildId: d320ce4e63925d698610ed423fc4b1f0e8ed51f1)
    #18 0x55778d784c94 in _start (/usr/src/barretenberg/cpp/build-msan/bin/eccvm_tests+0x35c94) (BuildId: e8715fcc9b34a72857a9238cebccb8b56fc07000)

  Uninitialized value was stored to memory at
    #0 0x55778e4fe824 in bb::field<bb::Bn254FqParams>::mac(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long&, unsigned long&) /usr/src/barretenberg/cpp/src/barretenberg/ecc/curves/bn254/../../fields/./field_impl_generic.hpp:48:21
    #1 0x55778e4fe824 in bb::field<bb::Bn254FqParams>::montgomery_mul(bb::field<bb::Bn254FqParams> const&) const /usr/src/barretenberg/cpp/src/barretenberg/ecc/curves/bn254/../../fields/./field_impl_generic.hpp:461:5
    #2 0x55778e4fe824 in bb::field<bb::Bn254FqParams>::operator*(bb::field<bb::Bn254FqParams> const&) const /usr/src/barretenberg/cpp/src/barretenberg/ecc/curves/bn254/../../fields/./field_impl.hpp:33:16
    #3 0x55778e4fe824 in bb::ECCVMProver_<bb::ECCVMFlavor>::execute_transcript_consistency_univariate_opening_round() /usr/src/barretenberg/cpp/src/barretenberg/eccvm/eccvm_prover.cpp:265:36
    #4 0x55778e515f0d in bb::ECCVMProver_<bb::ECCVMFlavor>::construct_proof() /usr/src/barretenberg/cpp/src/barretenberg/eccvm/eccvm_prover.cpp:305:5
    #5 0x55778db7fb8d in ECCVMComposerTests_BaseCase_Test<bb::ECCVMFlavor>::TestBody() /usr/src/barretenberg/cpp/src/barretenberg/eccvm/eccvm_composer.test.cpp:80:25
    #6 0x55779031a794 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2621:10
    #7 0x5577901770e1 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2657:14
    #8 0x5577900df6a8 in testing::Test::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2696:5
    #9 0x5577900e2d1b in testing::TestInfo::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2845:11
    #10 0x5577900e5c7b in testing::TestSuite::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:3004:30
    #11 0x557790125f26 in testing::internal::UnitTestImpl::RunAllTests() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:5890:44
    #12 0x55779031ded4 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2621:10
    #13 0x557790186f6d in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2657:14
    #14 0x557790123c5f in testing::UnitTest::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:5455:10
    #15 0x557790325b60 in RUN_ALL_TESTS() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/include/gtest/gtest.h:2314:73
    #16 0x557790325b49 in main /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest_main.cc:63:10
    #17 0x7ffb6d04ea8f  (/lib/x86_64-linux-gnu/libc.so.6+0x23a8f) (BuildId: d320ce4e63925d698610ed423fc4b1f0e8ed51f1)

  Uninitialized value was stored to memory at
    #0 0x55778e4fe521 in bb::field<bb::Bn254FqParams>::montgomery_mul(bb::field<bb::Bn254FqParams> const&) const /usr/src/barretenberg/cpp/src/barretenberg/ecc/curves/bn254/../../fields/./field_impl_generic.hpp
    #1 0x55778e4fe521 in bb::field<bb::Bn254FqParams>::operator*(bb::field<bb::Bn254FqParams> const&) const /usr/src/barretenberg/cpp/src/barretenberg/ecc/curves/bn254/../../fields/./field_impl.hpp:33:16
    #2 0x55778e4fe521 in bb::ECCVMProver_<bb::ECCVMFlavor>::execute_transcript_consistency_univariate_opening_round() /usr/src/barretenberg/cpp/src/barretenberg/eccvm/eccvm_prover.cpp:265:36
    #3 0x55778e515f0d in bb::ECCVMProver_<bb::ECCVMFlavor>::construct_proof() /usr/src/barretenberg/cpp/src/barretenberg/eccvm/eccvm_prover.cpp:305:5
    #4 0x55778db7fb8d in ECCVMComposerTests_BaseCase_Test<bb::ECCVMFlavor>::TestBody() /usr/src/barretenberg/cpp/src/barretenberg/eccvm/eccvm_composer.test.cpp:80:25
    #5 0x55779031a794 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2621:10
    #6 0x5577901770e1 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2657:14
    #7 0x5577900df6a8 in testing::Test::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2696:5
    #8 0x5577900e2d1b in testing::TestInfo::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2845:11
    #9 0x5577900e5c7b in testing::TestSuite::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:3004:30
    #10 0x557790125f26 in testing::internal::UnitTestImpl::RunAllTests() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:5890:44
    #11 0x55779031ded4 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2621:10
    #12 0x557790186f6d in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2657:14
    #13 0x557790123c5f in testing::UnitTest::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:5455:10
    #14 0x557790325b60 in RUN_ALL_TESTS() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/include/gtest/gtest.h:2314:73
    #15 0x557790325b49 in main /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest_main.cc:63:10
    #16 0x7ffb6d04ea8f  (/lib/x86_64-linux-gnu/libc.so.6+0x23a8f) (BuildId: d320ce4e63925d698610ed423fc4b1f0e8ed51f1)

  Uninitialized value was stored to memory at
    #0 0x55778e4fd680 in bb::field<bb::Bn254FqParams>::montgomery_mul(bb::field<bb::Bn254FqParams> const&) const /usr/src/barretenberg/cpp/src/barretenberg/ecc/curves/bn254/../../fields/./field_impl_generic.hpp:458:7
    #1 0x55778e4fd680 in bb::field<bb::Bn254FqParams>::operator*(bb::field<bb::Bn254FqParams> const&) const /usr/src/barretenberg/cpp/src/barretenberg/ecc/curves/bn254/../../fields/./field_impl.hpp:33:16
    #2 0x55778e4fd680 in bb::ECCVMProver_<bb::ECCVMFlavor>::execute_transcript_consistency_univariate_opening_round() /usr/src/barretenberg/cpp/src/barretenberg/eccvm/eccvm_prover.cpp:265:36
    #3 0x55778e515f0d in bb::ECCVMProver_<bb::ECCVMFlavor>::construct_proof() /usr/src/barretenberg/cpp/src/barretenberg/eccvm/eccvm_prover.cpp:305:5
    #4 0x55778db7fb8d in ECCVMComposerTests_BaseCase_Test<bb::ECCVMFlavor>::TestBody() /usr/src/barretenberg/cpp/src/barretenberg/eccvm/eccvm_composer.test.cpp:80:25
    #5 0x55779031a794 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2621:10
    #6 0x5577901770e1 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2657:14
    #7 0x5577900df6a8 in testing::Test::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2696:5
    #8 0x5577900e2d1b in testing::TestInfo::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2845:11
    #9 0x5577900e5c7b in testing::TestSuite::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:3004:30
    #10 0x557790125f26 in testing::internal::UnitTestImpl::RunAllTests() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:5890:44
    #11 0x55779031ded4 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2621:10
    #12 0x557790186f6d in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2657:14
    #13 0x557790123c5f in testing::UnitTest::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:5455:10
    #14 0x557790325b60 in RUN_ALL_TESTS() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/include/gtest/gtest.h:2314:73
    #15 0x557790325b49 in main /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest_main.cc:63:10
    #16 0x7ffb6d04ea8f  (/lib/x86_64-linux-gnu/libc.so.6+0x23a8f) (BuildId: d320ce4e63925d698610ed423fc4b1f0e8ed51f1)

  Uninitialized value was stored to memory at
    #0 0x55778e4fd453 in bb::field<bb::Bn254FqParams>::mac_mini(unsigned long, unsigned long, unsigned long, unsigned long&, unsigned long&) /usr/src/barretenberg/cpp/src/barretenberg/ecc/curves/bn254/../../fields/./field_impl_generic.hpp:82:9
    #1 0x55778e4fd453 in bb::field<bb::Bn254FqParams>::montgomery_mul(bb::field<bb::Bn254FqParams> const&) const /usr/src/barretenberg/cpp/src/barretenberg/ecc/curves/bn254/../../fields/./field_impl_generic.hpp:457:5
    #2 0x55778e4fd453 in bb::field<bb::Bn254FqParams>::operator*(bb::field<bb::Bn254FqParams> const&) const /usr/src/barretenberg/cpp/src/barretenberg/ecc/curves/bn254/../../fields/./field_impl.hpp:33:16
    #3 0x55778e4fd453 in bb::ECCVMProver_<bb::ECCVMFlavor>::execute_transcript_consistency_univariate_opening_round() /usr/src/barretenberg/cpp/src/barretenberg/eccvm/eccvm_prover.cpp:265:36
    #4 0x55778e515f0d in bb::ECCVMProver_<bb::ECCVMFlavor>::construct_proof() /usr/src/barretenberg/cpp/src/barretenberg/eccvm/eccvm_prover.cpp:305:5
    #5 0x55778db7fb8d in ECCVMComposerTests_BaseCase_Test<bb::ECCVMFlavor>::TestBody() /usr/src/barretenberg/cpp/src/barretenberg/eccvm/eccvm_composer.test.cpp:80:25
    #6 0x55779031a794 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2621:10
    #7 0x5577901770e1 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2657:14
    #8 0x5577900df6a8 in testing::Test::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2696:5
    #9 0x5577900e2d1b in testing::TestInfo::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2845:11
    #10 0x5577900e5c7b in testing::TestSuite::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:3004:30
    #11 0x557790125f26 in testing::internal::UnitTestImpl::RunAllTests() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:5890:44
    #12 0x55779031ded4 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2621:10
    #13 0x557790186f6d in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2657:14
    #14 0x557790123c5f in testing::UnitTest::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:5455:10
    #15 0x557790325b60 in RUN_ALL_TESTS() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/include/gtest/gtest.h:2314:73
    #16 0x557790325b49 in main /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest_main.cc:63:10
    #17 0x7ffb6d04ea8f  (/lib/x86_64-linux-gnu/libc.so.6+0x23a8f) (BuildId: d320ce4e63925d698610ed423fc4b1f0e8ed51f1)

  Uninitialized value was stored to memory at
    #0 0x55778e4fd32d in bb::field<bb::Bn254FqParams>::mac_mini(unsigned long, unsigned long, unsigned long, unsigned long&, unsigned long&) /usr/src/barretenberg/cpp/src/barretenberg/ecc/curves/bn254/../../fields/./field_impl_generic.hpp:81:21
    #1 0x55778e4fd32d in bb::field<bb::Bn254FqParams>::montgomery_mul(bb::field<bb::Bn254FqParams> const&) const /usr/src/barretenberg/cpp/src/barretenberg/ecc/curves/bn254/../../fields/./field_impl_generic.hpp:457:5
    #2 0x55778e4fd32d in bb::field<bb::Bn254FqParams>::operator*(bb::field<bb::Bn254FqParams> const&) const /usr/src/barretenberg/cpp/src/barretenberg/ecc/curves/bn254/../../fields/./field_impl.hpp:33:16
    #3 0x55778e4fd32d in bb::ECCVMProver_<bb::ECCVMFlavor>::execute_transcript_consistency_univariate_opening_round() /usr/src/barretenberg/cpp/src/barretenberg/eccvm/eccvm_prover.cpp:265:36
    #4 0x55778e515f0d in bb::ECCVMProver_<bb::ECCVMFlavor>::construct_proof() /usr/src/barretenberg/cpp/src/barretenberg/eccvm/eccvm_prover.cpp:305:5
    #5 0x55778db7fb8d in ECCVMComposerTests_BaseCase_Test<bb::ECCVMFlavor>::TestBody() /usr/src/barretenberg/cpp/src/barretenberg/eccvm/eccvm_composer.test.cpp:80:25
    #6 0x55779031a794 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2621:10
    #7 0x5577901770e1 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2657:14
    #8 0x5577900df6a8 in testing::Test::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2696:5
    #9 0x5577900e2d1b in testing::TestInfo::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2845:11
    #10 0x5577900e5c7b in testing::TestSuite::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:3004:30
    #11 0x557790125f26 in testing::internal::UnitTestImpl::RunAllTests() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:5890:44
    #12 0x55779031ded4 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2621:10
    #13 0x557790186f6d in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2657:14
    #14 0x557790123c5f in testing::UnitTest::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:5455:10
    #15 0x557790325b60 in RUN_ALL_TESTS() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/include/gtest/gtest.h:2314:73
    #16 0x557790325b49 in main /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest_main.cc:63:10
    #17 0x7ffb6d04ea8f  (/lib/x86_64-linux-gnu/libc.so.6+0x23a8f) (BuildId: d320ce4e63925d698610ed423fc4b1f0e8ed51f1)

  Uninitialized value was stored to memory at
    #0 0x55778e4fd0d4 in bb::field<bb::Bn254FqParams>::montgomery_mul(bb::field<bb::Bn254FqParams> const&) const /usr/src/barretenberg/cpp/src/barretenberg/ecc/curves/bn254/../../fields/./field_impl_generic.hpp
    #1 0x55778e4fd0d4 in bb::field<bb::Bn254FqParams>::operator*(bb::field<bb::Bn254FqParams> const&) const /usr/src/barretenberg/cpp/src/barretenberg/ecc/curves/bn254/../../fields/./field_impl.hpp:33:16
    #2 0x55778e4fd0d4 in bb::ECCVMProver_<bb::ECCVMFlavor>::execute_transcript_consistency_univariate_opening_round() /usr/src/barretenberg/cpp/src/barretenberg/eccvm/eccvm_prover.cpp:265:36
    #3 0x55778e515f0d in bb::ECCVMProver_<bb::ECCVMFlavor>::construct_proof() /usr/src/barretenberg/cpp/src/barretenberg/eccvm/eccvm_prover.cpp:305:5
    #4 0x55778db7fb8d in ECCVMComposerTests_BaseCase_Test<bb::ECCVMFlavor>::TestBody() /usr/src/barretenberg/cpp/src/barretenberg/eccvm/eccvm_composer.test.cpp:80:25
    #5 0x55779031a794 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2621:10
    #6 0x5577901770e1 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2657:14
    #7 0x5577900df6a8 in testing::Test::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2696:5
    #8 0x5577900e2d1b in testing::TestInfo::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2845:11
    #9 0x5577900e5c7b in testing::TestSuite::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:3004:30
    #10 0x557790125f26 in testing::internal::UnitTestImpl::RunAllTests() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:5890:44
    #11 0x55779031ded4 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2621:10
    #12 0x557790186f6d in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:2657:14
    #13 0x557790123c5f in testing::UnitTest::Run() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest.cc:5455:10
    #14 0x557790325b60 in RUN_ALL_TESTS() /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/include/gtest/gtest.h:2314:73
    #15 0x557790325b49 in main /usr/src/barretenberg/cpp/build-msan/_deps/gtest-src/googletest/src/gtest_main.cc:63:10
    #16 0x7ffb6d04ea8f  (/lib/x86_64-linux-gnu/libc.so.6+0x23a8f) (BuildId: d320ce4e63925d698610ed423fc4b1f0e8ed51f1)

  Uninitialized value was created by an allocation of 'univariate_evaluations' in the stack frame
    #0 0x55778e4f0b81 in bb::ECCVMProver_<bb::ECCVMFlavor>::execute_transcript_consistency_univariate_opening_round() /usr/src/barretenberg/cpp/src/barretenberg/eccvm/eccvm_prover.cpp:257:5

SUMMARY: MemorySanitizer: use-of-uninitialized-value /usr/src/barretenberg/cpp/src/barretenberg/ecc/curves/bn254/../../fields/./field_impl_generic.hpp:467:12 in bb::field<bb::Bn254FqParams>::montgomery_mul(bb::field<bb::Bn254FqParams> const&) const
Exiting
```

**Comment by ludamad** [comment]
<img width="701" alt="Screenshot 2024-02-20 at 3 12 09 PM" src="https://github.com/AztecProtocol/barretenberg/assets/163993/904b248e-f3e8-4744-a943-bf46cc5ec92b">
the relevant code

@zac-williamson  can you look at this? eval here is uninitialized

**Comment by ludamad** [comment]
FIxed
